[package]
name = "cganomaly"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
reqwest = { version = "0.11", features = ["json", "blocking"] }
chrono = "0.4"
